channels:
  - defaults
  - conda-forge
dependencies:
- python=3.5
- numpy>=1.11.0
- scipy>=0.18.1
- scikit-learn>=0.19
- pandas=0.19.1
- matplotlib=2.0.0
- traits=4.6
- jinja2=2.8
- sphinx>=1.5.3
- sphinx_rtd_theme>=0.2.4

- pip:
	- niworkflows>=0.3.13
